<a href="https://colab.research.google.com/github/muhammed-bayat/EEG_Classification_Deeplearning/blob/master/LSTM_AR_DATA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
pip install git+https://github.com/forrestbao/pyeeg.git

  Cloning https://github.com/forrestbao/pyeeg.git to /tmp/pip-req-build-pqzzixyt
  Running command git clone -q https://github.com/forrestbao/pyeeg.git /tmp/pip-req-build-pqzzixyt
  Created wheel for pyeeg: filename=pyeeg-0.4.4-py2.py3-none-any.whl size=28133 sha256=2b15da6e64447a9e735fc57578989e21f2644a2e877e88699c18d8c6c2e56e2d
  Stored in directory: /tmp/pip-ephem-wheel-cache-yimc6l87/wheels/2d/3f/ad/106d4fc80b61d1ea1fc18e76e7439fd98aa043d83d58eae741
Successfully built pyeeg


In [12]:
 import numpy as np

import pickle as pickle
import pandas as pd
import pyeeg as pe

In [13]:
from sklearn.preprocessing import normalize


In [14]:
import scipy.io as sio


In [15]:
channel = [1,2,3,4,6,11,13,17,19,20,21,25,29,31] #14 Channels 
band = [4,8,12,16,25,45] #5 bands
window_size = 256 #Averaging band power of 2 sec
step_size = 16 #Each 0.125 sec update once
sample_rate = 128 #Sampling rate of 128 Hz
## Load only 22/32 participants with frontal videos recorded
subjectList = ['01']
#List of subjects

In [16]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [17]:
cd ..

/


In [18]:
def FFT_Processing (sub, channel, band, window_size, step_size, sample_rate):
    '''
    arguments:  string subject
                list channel indice
                list band
                int window size for FFT
                int step size for FFT
                int sample rate for FFT
    return:     void
    '''
    meta = []

    
dataPath = '/content/drive/MyDrive/TEST/matlab_data/testAR/AR_DATA.MAT'

meta = []
filename = dataPath

mat_contents = sio.loadmat(filename)
with open(filename) as file:

    subject =sio.loadmat(filename)

    for i in range (0,1):
        # loop over 0-39 trails
        data = subject["veriS_AR"][i]
        labels = subject["veriS_Kitap"][i]
        start = 0;

    
  

In [19]:
for subjects in subjectList:
    FFT_Processing (subjects, channel, band, window_size, step_size, sample_rate)

In [20]:
mat_contents["veriS_AR"]

array([[(array([[1]], dtype=uint8), array([[1]], dtype=uint8), array([[1]], dtype=uint8), array([[2]], dtype=uint8), array([[3]], dtype=uint8), array([[2]], dtype=uint8), array([[1]], dtype=uint8), array([[4143.461426, 4130.512695, 4133.846191, ..., 4140.256348,
        4166.153809, 4127.94873 ],
       [4144.615234, 4137.94873 , 4141.282227, ..., 4128.205078,
        4133.077148, 4102.563965],
       [4150.256348, 4142.307617, 4135.      , ..., 4102.307617,
        4117.179688, 4095.769287],
       ...,
       [4151.410156, 4147.436035, 4144.487305, ..., 4172.820313,
        4192.94873 , 4178.461426],
       [4142.692383, 4113.205078, 4111.666504, ..., 4104.487305,
        4136.538574, 4096.538574],
       [4164.871582, 4144.615234, 4147.820313, ..., 2234.615479,
        2280.769287, 2269.487061]])),
        (array([[1]], dtype=uint8), array([[1]], dtype=uint8), array([[2]], dtype=uint8), array([[2]], dtype=uint8), array([[7]], dtype=uint8), array([[7]], dtype=uint8), array([[7]], dty

In [21]:
data.shape

(30,)

In [22]:
mat_contents["veriS_AR"]

array([[(array([[1]], dtype=uint8), array([[1]], dtype=uint8), array([[1]], dtype=uint8), array([[2]], dtype=uint8), array([[3]], dtype=uint8), array([[2]], dtype=uint8), array([[1]], dtype=uint8), array([[4143.461426, 4130.512695, 4133.846191, ..., 4140.256348,
        4166.153809, 4127.94873 ],
       [4144.615234, 4137.94873 , 4141.282227, ..., 4128.205078,
        4133.077148, 4102.563965],
       [4150.256348, 4142.307617, 4135.      , ..., 4102.307617,
        4117.179688, 4095.769287],
       ...,
       [4151.410156, 4147.436035, 4144.487305, ..., 4172.820313,
        4192.94873 , 4178.461426],
       [4142.692383, 4113.205078, 4111.666504, ..., 4104.487305,
        4136.538574, 4096.538574],
       [4164.871582, 4144.615234, 4147.820313, ..., 2234.615479,
        2280.769287, 2269.487061]])),
        (array([[1]], dtype=uint8), array([[1]], dtype=uint8), array([[2]], dtype=uint8), array([[2]], dtype=uint8), array([[7]], dtype=uint8), array([[7]], dtype=uint8), array([[7]], dty

In [23]:
labels.shape

(30,)

In [24]:
type(mat_contents['veriS_Kitap']),mat_contents['veriS_Kitap'].shape

(numpy.ndarray, (1, 30))

In [25]:
type(mat_contents['veriS_Kitap'][0][0]),mat_contents['veriS_Kitap'][0][0].shape

(numpy.void, ())

In [26]:
print(mat_contents['veriS_Kitap'][0][0])

(array([[1]], dtype=uint8), array([[1]], dtype=uint8), array([[1]], dtype=uint8), array([[1]], dtype=uint8), array([[4]], dtype=uint8), array([[4]], dtype=uint8), array([[2]], dtype=uint8), array([[4143.461426, 4130.512695, 4133.846191, ..., 4140.256348,
        4166.153809, 4127.94873 ],
       [4144.615234, 4137.94873 , 4141.282227, ..., 4128.205078,
        4133.077148, 4102.563965],
       [4150.256348, 4142.307617, 4135.      , ..., 4102.307617,
        4117.179688, 4095.769287],
       ...,
       [4151.410156, 4147.436035, 4144.487305, ..., 4172.820313,
        4192.94873 , 4178.461426],
       [4142.692383, 4113.205078, 4111.666504, ..., 4104.487305,
        4136.538574, 4096.538574],
       [4164.871582, 4144.615234, 4147.820313, ..., 2234.615479,
        2280.769287, 2269.487061]]))


In [27]:
mat_contents['veriS_Kitap'][0][0]['subjectNo'], mat_contents['veriS_Kitap'][0][0]['data0']

(array([[1]], dtype=uint8),
 array([[4143.461426, 4130.512695, 4133.846191, ..., 4140.256348,
         4166.153809, 4127.94873 ],
        [4144.615234, 4137.94873 , 4141.282227, ..., 4128.205078,
         4133.077148, 4102.563965],
        [4150.256348, 4142.307617, 4135.      , ..., 4102.307617,
         4117.179688, 4095.769287],
        ...,
        [4151.410156, 4147.436035, 4144.487305, ..., 4172.820313,
         4192.94873 , 4178.461426],
        [4142.692383, 4113.205078, 4111.666504, ..., 4104.487305,
         4136.538574, 4096.538574],
        [4164.871582, 4144.615234, 4147.820313, ..., 2234.615479,
         2280.769287, 2269.487061]]))

In [28]:
mat_contents['veriS_Kitap'][0][0]['subjectNo'].flat[0]

1

In [29]:
class_names = [i.flat[0] for i in mat_contents['veriS_Kitap'][0]['data0']]

In [30]:
[item.flat[0] for item in mat_contents['veriS_Kitap'][0][0]]

[1, 1, 1, 1, 4, 4, 2, 4143.461426]

In [31]:
data = [[row.flat[0] for row in line] for line in mat_contents['veriS_Kitap'][0]]

In [32]:
columns = ['subjectNo','kitapNo', 'stimNo_kitap', 'stimNo_AR', 'valence','arousal', 'dominance', 'data0']
df_train = pd.DataFrame(data, columns=columns)

In [33]:
data

[[1, 1, 1, 1, 4, 4, 2, 4143.461426],
 [1, 1, 2, 1, 4, 2, 4, 4208.333496],
 [1, 1, 3, 1, 3, 1, 4, 4124.487305],
 [1, 1, 4, 1, 6, 6, 2, 4169.358887],
 [1, 1, 5, 1, 6, 7, 3, 4124.487305],
 [1, 1, 6, 1, 3, 1, 4, 4159.102539],
 [1, 1, 7, 1, 4, 1, 1, 4078.974365],
 [1, 1, 8, 1, 5, 5, 5, 4143.974121],
 [1, 1, 9, 1, 6, 8, 6, 4110.897461],
 [1, 1, 10, 1, 4, 1, 1, 4121.153809],
 [2, 2, 5, 1, 6, 3, 1, 4110.512695],
 [2, 2, 6, 1, 2, 7, 2, 4161.794922],
 [2, 2, 10, 1, 8, 6, 1, 4125.769043],
 [2, 2, 1, 1, 5, 2, 1, 4255.897461],
 [2, 2, 4, 1, 8, 5, 2, 4342.179688],
 [2, 2, 7, 1, 2, 7, 3, 4282.179688],
 [2, 2, 3, 1, 5, 2, 1, 4265.256348],
 [2, 2, 8, 1, 3, 5, 2, 4142.820313],
 [2, 2, 2, 1, 5, 2, 1, 4144.743652],
 [2, 2, 9, 1, 2, 7, 3, 4258.461426],
 [3, 2, 5, 1, 9, 8, 8, 4126.282227],
 [3, 2, 6, 1, 8, 1, 2, 4169.102539],
 [3, 2, 10, 1, 9, 9, 7, 4141.410156],
 [3, 2, 1, 1, 9, 8, 8, 4198.717773],
 [3, 2, 4, 1, 2, 1, 1, 4113.846191],
 [3, 2, 7, 1, 8, 8, 8, 4150.0],
 [3, 2, 3, 1, 6, 6, 6, 4295.0],
 [3, 2, 

In [34]:
data.count

<function list.count>

In [35]:
df_train

subjectNo  kitapNo  stimNo_kitap  ...  arousal  dominance        data0
0           1        1             1  ...        4          2  4143.461426
1           1        1             2  ...        2          4  4208.333496
2           1        1             3  ...        1          4  4124.487305
3           1        1             4  ...        6          2  4169.358887
4           1        1             5  ...        7          3  4124.487305
5           1        1             6  ...        1          4  4159.102539
6           1        1             7  ...        1          1  4078.974365
7           1        1             8  ...        5          5  4143.974121
8           1        1             9  ...        8          6  4110.897461
9           1        1            10  ...        1          1  4121.153809
10          2        2             5  ...        3          1  4110.512695
11          2        2             6  ...        7          2  4161.794922
12          2        2            10  ...        6          1  4125.769043
13          2        2             1  ...        2          1  4255.897461
14          2        2             4  ...        5          2  4342.179688
15          2        2             7  ...        7          3  4282.179688
16          2        2             3  ...        2          1  4265.256348
17          2        2             8  ...        5          2  4142.820313
18          2        2             2  ...        2          1  4144.743652
19          2        2             9  ...        7          3  4258.461426
20          3        2             5  ...        8          8  4126.282227
21          3        2             6  ...        1          2  4169.102539
22          3        2            10  ...        9          7  4141.410156
23          3        2             1  ...        8          8  4198.717773
24          3        2             4  ...        1          1  4113.846191
25          3        2             7  ...        8          8  4150.000000
26          3        2             3  ...        6          6  4295.000000
27          3        2             8  ...        7          7  4135.000000
28          3        2             2  ...        8          7  4184.358887
29          3        2             9  ...        7          4  4114.230957

[30 rows x 8 columns]

In [36]:
labels=df_train.loc[::1,"valence":"dominance"]

labels

valence  arousal  dominance
0         4        4          2
1         4        2          4
2         3        1          4
3         6        6          2
4         6        7          3
5         3        1          4
6         4        1          1
7         5        5          5
8         6        8          6
9         4        1          1
10        6        3          1
11        2        7          2
12        8        6          1
13        5        2          1
14        8        5          2
15        2        7          3
16        5        2          1
17        3        5          2
18        5        2          1
19        2        7          3
20        9        8          8
21        8        1          2
22        9        9          7
23        9        8          8
24        2        1          1
25        8        8          8
26        6        6          6
27        6        7          7
28        8        8          7
29        8        7          4

In [37]:
data=df_train.loc[::1,"data0"]
data

0     4143.461426
1     4208.333496
2     4124.487305
3     4169.358887
4     4124.487305
5     4159.102539
6     4078.974365
7     4143.974121
8     4110.897461
9     4121.153809
10    4110.512695
11    4161.794922
12    4125.769043
13    4255.897461
14    4342.179688
15    4282.179688
16    4265.256348
17    4142.820313
18    4144.743652
19    4258.461426
20    4126.282227
21    4169.102539
22    4141.410156
23    4198.717773
24    4113.846191
25    4150.000000
26    4295.000000
27    4135.000000
28    4184.358887
29    4114.230957
Name: data0, dtype: float64

In [39]:
df=pd.DataFrame(data=data)
df.to_csv("data.csv",index=False)

df1=pd.DataFrame(data=labels)
df1.to_csv("label.csv",index=False)


In [40]:
ls

bin/      datalab/  label.csv  media/  root/  sys/                usr/
boot/     dev/      lib/       mnt/    run/   tensorflow-1.15.2/  var/
content/  etc/      lib32/     opt/    sbin/  tmp/
data.csv  home/     lib64/     proc/   srv/   tools/


In [41]:
x=data.values

In [42]:
x

array([4143.461426, 4208.333496, 4124.487305, 4169.358887, 4124.487305,
       4159.102539, 4078.974365, 4143.974121, 4110.897461, 4121.153809,
       4110.512695, 4161.794922, 4125.769043, 4255.897461, 4342.179688,
       4282.179688, 4265.256348, 4142.820313, 4144.743652, 4258.461426,
       4126.282227, 4169.102539, 4141.410156, 4198.717773, 4113.846191,
       4150.      , 4295.      , 4135.      , 4184.358887, 4114.230957])

In [43]:
labels.isnull().sum()


valence      0
arousal      0
dominance    0
dtype: int64

In [44]:
y_val=labels.loc[:,"valence"]

In [45]:
y_val

0     4
1     4
2     3
3     6
4     6
5     3
6     4
7     5
8     6
9     4
10    6
11    2
12    8
13    5
14    8
15    2
16    5
17    3
18    5
19    2
20    9
21    8
22    9
23    9
24    2
25    8
26    6
27    6
28    8
29    8
Name: valence, dtype: int64

In [46]:
y_val.unique()

array([4, 3, 6, 5, 2, 8, 9])

In [47]:
y_val.values

array([4, 4, 3, 6, 6, 3, 4, 5, 6, 4, 6, 2, 8, 5, 8, 2, 5, 3, 5, 2, 9, 8,
       9, 9, 2, 8, 6, 6, 8, 8])

In [48]:
x

array([4143.461426, 4208.333496, 4124.487305, 4169.358887, 4124.487305,
       4159.102539, 4078.974365, 4143.974121, 4110.897461, 4121.153809,
       4110.512695, 4161.794922, 4125.769043, 4255.897461, 4342.179688,
       4282.179688, 4265.256348, 4142.820313, 4144.743652, 4258.461426,
       4126.282227, 4169.102539, 4141.410156, 4198.717773, 4113.846191,
       4150.      , 4295.      , 4135.      , 4184.358887, 4114.230957])

In [49]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x.reshape(1, -1))
x = scaler.transform(x.reshape(1, -1))
 
 
from tensorflow.keras.utils import to_categorical
 
y = to_categorical(y_val)
y

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 

In [50]:
x = np.reshape(x, (x.shape[0],1,x.shape[1]))


In [51]:
x


array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [52]:
y.shape

(30, 10)

In [53]:
y

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 

In [54]:
x.shape

(1, 1, 30)

In [56]:
x

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [57]:
x =x.transpose()

In [58]:
"""x = x.reshape(x.shape[1:])
x
"""

ValueError: ignored

In [65]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x.reshape(-1,1), y, test_size = 0.2, random_state = 4)

In [66]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(24, 1)
(24, 10)
(6, 1)
(6, 10)


In [67]:
import keras

from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.layers import LSTM,BatchNormalization,Activation
model = Sequential()
model.add(LSTM(512, batch_input_shape = (None, None, x.shape[2]),return_sequences=True))


In [68]:
 x.shape[2]

1

In [69]:
 x.shape


(30, 1, 1)

In [70]:

model.add(BatchNormalization())
model.add(Dropout(0.3))

model.add(LSTM(256,activation="relu",return_sequences=True))
model.add(BatchNormalization())
model.add(Dropout(0.5))


model.add(LSTM(128,activation="relu",return_sequences=True))
model.add(BatchNormalization())
model.add(Dropout(0.3))

model.add(LSTM(64,activation="relu",return_sequences=True))
model.add(BatchNormalization())
model.add(Dropout(0.3))


model.add(LSTM(32,activation="relu"))
model.add(BatchNormalization())
model.add(Dropout(0.2))


model.add(Dense(1))
model.add(Activation('sigmoid'))

rmsprop =keras.optimizers.RMSprop(lr=0.0001, rho=0.9, epsilon=1e-08)
model.compile(loss='mean_squared_error',
                  optimizer=rmsprop,
                  metrics=['accuracy'])
#adam = keras.optimizers.Adam(lr=0.5, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)
#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_5 (LSTM)                (None, None, 512)         1052672   
_________________________________________________________________
batch_normalization_5 (Batch (None, None, 512)         2048      
_________________________________________________________________
dropout_5 (Dropout)          (None, None, 512)         0         
_________________________________________________________________
lstm_6 (LSTM)                (None, None, 256)         787456    
_________________________________________________________________
batch_normalization_6 (Batch (None, None, 256)         1024      
_________________________________________________________________
dropout_6 (Dropout)          (None, None, 256)         0         
_________________________________________________________________
lstm_7 (LSTM)                (None, None, 128)        

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


In [71]:
history = model.fit(x_train, y_train, epochs = 200, batch_size=512,validation_data= (x_test, y_test))


Epoch 1/200


ValueError: ignored